# Yarn config
# Building fails with global cache, use this to fix it
# https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-with-yarn-3-yarn-3-global-cache
nodeLinker: node-modules
