# REFERENCES:
# https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco
# https://github.com/rrbutani/use-nix-shell-action?tab=readme-ov-file#example
# https://kit.svelte.dev/docs/adapter-static#github-pages
# https://github.com/skywarth/country-routing-algorithm-demo-vue/blob/master/.github/workflows/deploy-to-github-actions.yml
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: Vercel Production Deployment
on:
    # Runs on pushes targeting the main branch
    push:
        branches: ["main"]
    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:
# Allow only one concurrent deployment, but don't cancel in-progress ones
concurrency:
    group: "pages"
    cancel-in-progress: false
jobs:
    deploy-prod:
        runs-on: ubuntu-latest
        environment:
            name: vercel
        env:
            # Vercel variables
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            # Set repo env variables for footer info
            PUBLIC_GITHUB_REPOSITORY: "${{ github.repository }}"
            PUBLIC_GITHUB_REF_NAME: "${{ github.ref_name }}"
            PUBLIC_GITHUB_SHA: "${{ github.sha }}"
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            # Setup Nix and enter the flake shell
          - name: Install Nix
            uses: cachix/install-nix-action@v18
            with:
                nix_path: nixpkgs=channel:nixos-unstable
          - name: Use Nix Shell
            uses: rrbutani/use-nix-shell-action@v1
            # Manually installing Yarn dependencies should be unnecessary
          - name: Pull Vercel Environment Information
            run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          - name: Build Project Artifacts
            run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            # Upload artifacts for deployment
          - name: Deploy Artifacts to Vercel
            run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
