# REFERENCES:
# https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco
# https://github.com/rrbutani/use-nix-shell-action?tab=readme-ov-file#example
# https://kit.svelte.dev/docs/adapter-static#github-pages
# https://github.com/skywarth/country-routing-algorithm-demo-vue/blob/master/.github/workflows/deploy-to-github-actions.yml

name: Deploy to GitHub Pages
on:
    # Runs on pushes targeting the main branch
    push:
        branches: ["master", "main"]
    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:
# Allow only one concurrent deployment, but don't cancel in-progress ones
concurrency:
    group: "pages"
    cancel-in-progress: false
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            # Setup Nix and enter the flake shell
          - name: Install Nix
            uses: cachix/install-nix-action@v18
            with:
                nix_path: nixpkgs=channel:nixos-unstable
          - name: Use Nix shell
            uses: rrbutani/use-nix-shell-action@v1
            # Install Yarn dependencies and build the website
          - name: Install dependencies
            run: yarn install
          - name: build
            env:
                # Set environment variables for footer info
                PUBLIC_GITHUB_REPOSITORY: "${{ github.repository }}"
                PUBLIC_GITHUB_REF_NAME: "${{ github.ref_name }}"
                PUBLIC_GITHUB_SHA: "${{ github.sha }}"
            run: yarn run build
            # Upload artifacts for deployment
          - name: Upload Artifacts
            uses: actions/upload-pages-artifact@v3
            with:
                path: "build/"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: "${{ steps.deployment.outputs.page_url }}"
        steps:
          - name: deploy
            id: deployment
            uses: actions/deploy-pages@v4
